name: 'cancel-by-process'
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Run processExit.js
        run: node scripts/processExit.js

      - name: Echo Hello World
        run: echo "Hello World"